spring:
  cloud:
    gateway:
      # 配置route转发规则
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - Path=/**