
server:
  port: 9000
spring:
  application:
    name: service-product
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
